// Generated by scripts/update-model-prices.mjs from https://models.dev/api.json. Do not edit by hand.
import type { ModelPrice } from "./model-prices";

export const modelPricesFetchedAt = "2026-09-26";

export const modelPrices: ModelPrice[] = [
  {
    "id": "claude-opus-5-5",
    "provider": "anthropic",
    "providerName": "Anthropic",
    "label": "Claude Opus 5.5",
    "input": 4,
    "output": 20,
    "cacheRead": 0.2,
    "claude": true
  },
  {
    "id": "claude-sonnet-5",
    "provider": "anthropic",
    "providerName": "Anthropic",
    "label": "Claude Sonnet 5",
    "input": 2,
    "output": 10,
    "cacheRead": 0.2,
    "claude": true
  },
  {
    "id": "claude-haiku-4-5",
    "provider": "anthropic",
    "providerName": "Anthropic",
    "label": "Claude Haiku 4.5",
    "input": 1,
    "output": 5,
    "cacheRead": 0.1,
    "claude": true
  },
  {
    "id": "gpt-6-sol",
    "provider": "openai",
    "providerName": "OpenAI",
    "label": "GPT-6 Sol",
    "input": 2,
    "output": 10,
    "cacheRead": 0.2,
    "claude": false
  },
  {
    "id": "gpt-6-luna",
    "provider": "openai",
    "providerName": "OpenAI",
    "label": "GPT-6 Luna",
    "input": 0.1,
    "output": 0.5,
    "cacheRead": 0.01,
    "claude": false
  },
  {
    "id": "gemini-3.1-pro-preview",
    "provider": "google",
    "providerName": "Google",
    "label": "Gemini 3.1 Pro",
    "input": 2,
    "output": 12,
    "cacheRead": 0.2,
    "claude": false
  },
  {
    "id": "gemini-3.8-flash",
    "provider": "google",
    "providerName": "Google",
    "label": "Gemini 3.8 Flash",
    "input": 0.75,
    "output": 3.75,
    "cacheRead": 0.075,
    "claude": false
  },
  {
    "id": "deepseek-v4-pro",
    "provider": "deepseek",
    "providerName": "DeepSeek",
    "label": "DeepSeek V4 Pro",
    "input": 0.435,
    "output": 0.87,
    "cacheRead": 0.003625,
    "claude": false
  },
  {
    "id": "deepseek-v4-flash",
    "provider": "deepseek",
    "providerName": "DeepSeek",
    "label": "DeepSeek V4 Flash",
    "input": 0.15,
    "output": 0.6,
    "cacheRead": 0.003,
    "claude": false
  },
  {
    "id": "glm-5.3",
    "provider": "zai",
    "providerName": "Z.AI",
    "label": "GLM 5.3",
    "input": 1.4,
    "output": 4.4,
    "cacheRead": 0.26,
    "claude": false
  },
  {
    "id": "kimi-k3",
    "provider": "moonshotai",
    "providerName": "Moonshot AI",
    "label": "Kimi K3",
    "input": 3,
    "output": 15,
    "cacheRead": 0.3,
    "claude": false
  },
  {
    "id": "MiniMax-M3",
    "provider": "minimax",
    "providerName": "MiniMax (minimax.io)",
    "label": "MiniMax M3",
    "input": 0.3,
    "output": 1.2,
    "cacheRead": 0.06,
    "claude": false
  },
  {
    "id": "qwen3.8-max",
    "provider": "alibaba",
    "providerName": "Alibaba",
    "label": "Qwen3.8 Max",
    "input": 2,
    "output": 6,
    "cacheRead": 0.25,
    "claude": false
  },
  {
    "id": "grok-4.7",
    "provider": "xai",
    "providerName": "xAI",
    "label": "Grok 4.7",
    "input": 2,
    "output": 6,
    "cacheRead": 0.5,
    "claude": false
  },
  {
    "id": "mistral-medium-latest",
    "provider": "mistral",
    "providerName": "Mistral",
    "label": "Mistral Medium",
    "input": 1.5,
    "output": 7.5,
    "cacheRead": null,
    "claude": false
  }
];
